springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

app:
  security:
    public-endpoints: >
      "/auth/phone/check",
      "/auth/login",
      "/auth/register/verify-otp",
      "/auth/register/set-password",
      "/auth/forgot-password",
      "/auth/reset-password",
      "/auth/refresh-token",
      "/users/register",
      "/users/verify-registration",
      "/users/resend-verification",
      "/v3/api-docs/**",
      "/swagger-ui/**",
      "/swagger-ui.html",
      "/actuator/**"
