name: metro-bus-ops

services:
  postgres:
    image: postgres:latest
    container_name: auth-ops-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${APP_TIMEZONE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    networks:
      - app-network

  afc-postgres:
    image: postgres:latest
    container_name: afc-ops-postgres
    environment:
      POSTGRES_USER: ${AFC_DB_USER}
      POSTGRES_PASSWORD: ${AFC_DB_PASSWORD}
      POSTGRES_DB: ${AFC_DB_NAME}
      TZ: ${APP_TIMEZONE}
    ports:
      - "${AFC_DB_PORT}:5432"
    volumes:
      - ./data/afc-postgres:/var/lib/postgresql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-ops
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes
    environment:
      TZ: ${APP_TIMEZONE}
    volumes:
      - ./data/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
