server:
  port: 8082
  servlet:
    context-path: /vdt

spring:
  application:
    name: afc-ops-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${AFC_DB_HOST}:${AFC_DB_PORT}/${AFC_DB_NAME}
    username: ${AFC_DB_USER}
    password: ${AFC_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false # true for debug
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics"
  endpoint:
    health:
      show-details: when_authorized

app:
  domain-name: localhost
  timezone: ${APP_TIMEZONE}
  init:
    enabled: false
    sync-auth-permissions-enabled: false
  message-broker:
    auth-permission-sync:
      exchange: auth.ops
      queue: auth.permission-sync
      routing-key: auth.permission-sync
    level5-card-sync:
      exchange: afc.exchange
      queue: afc.level5-card-sync
      routing-keys: "card.status.changed,blacklist.*,sync.card.all"
    level5-ticket-sync:
      exchange: afc.exchange
      queue: afc.level5-ticket-sync
      routing-keys: "ticket.*,sync.ticket.all"
    level5-entitlement-sync:
      exchange: afc.exchange
      queue: afc.level5-entitlement-sync
      routing-keys: "ticket.*,sync.ticket.all"
    level5-operator-sync:
      exchange: afc.exchange
      queue: afc.level5-operator-sync
      routing-keys: "sync.operator.all"
  security:
    csrf-header-name: X-CSRF-TOKEN
    csrf-cookie-name: XSRF-TOKEN
    access-token-cookie-name: accessToken
    access-token-secret-key: ${JWT_ACCESS_SECRET_KEY}
    access-token-expiration: 3600000
    cors-allowed-origins: "http://localhost:3000"
