springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  show-actuator: true

app:
  security:
    public-endpoints: >
      "/sync-operator-manager-role-permissions",
      "/swagger-ui/**",
      "/v3/api-docs/**",
      "/actuator/health"
